# vi mode
set -o vi

# path to oh-my-zsh configuration.
ZSH=${HOME}/.oh-my-zsh

# auto-update oh-my-zsh without prompting
DISABLE_UPDATE_PROMPT=true

# set name of the theme to load (in ~/.oh-my-zsh/themes/)
ZSH_THEME="oneend"

# plugins to load (from oh-my-zsh)
plugins=(git zsh-syntax-highlighting)

# source other files
source ${ZSH}/oh-my-zsh.sh
source ${HOME}/.zsh-alias

# disable autocorrect
unsetopt correct_all

# other settings
export LSCOLORS=hxfxcxdxbxegedabagacad
export PATH="/usr/local/bin:/usr/local/sbin:$PATH:/usr/local/share/npm/bin"
export EDITOR="vim"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# configure chruby, make 2.0 the default, but let it auto-switch based on .ruby-version files
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
chruby ruby-2.0

# configure pyenv (it alters PATH, so it needs to be set after it)
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# source z
source "$(brew --prefix)/etc/profile.d/z.sh"
