############
# settings #
############

# vi mode
set -o vi

# oh-my-zsh
DISABLE_UPDATE_PROMPT=true # auto-update without prompting
ZSH_THEME="oneend" # set name of the theme to load (in ~/.oh-my-zsh/themes/)
plugins=(git zsh-syntax-highlighting) # plugins to load
source ${HOME}/.oh-my-zsh/oh-my-zsh.sh # load it

# source alias and functions
source ${HOME}/.zsh-alias

# disable autocorrect
unsetopt correct_all

# other settings
export LSCOLORS=hxfxcxdxbxegedabagacad
export PATH="/usr/local/bin:/usr/local/sbin:$PATH:/usr/local/share/npm/bin"
export EDITOR="subl"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# configure chruby, make 2.0 the default, but let it auto-switch based on .ruby-version files
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
chruby ruby-2.0

# configure pyenv (it alters PATH, so it needs to be set after it)
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# source z
source "$(brew --prefix)/etc/profile.d/z.sh"