# oh-my-zsh
ZSH=${HOME}/.oh-my-zsh # config dir
DISABLE_UPDATE_PROMPT=true # auto-update without prompting
ZSH_THEME="oneend" # set name of the theme to load (in ~/.oh-my-zsh/themes/)
plugins=(brew git git-extras sublime vi-mode zsh-syntax-highlighting) # plugins to load
source ${ZSH}/oh-my-zsh.sh # load it

# source aliases and functions
source ${HOME}/.zsh-alias

# other settings
unsetopt correct_all # disable autocorrect
export LSCOLORS=hxfxcxdxbxegedabagacad
export PATH="/usr/local/bin:/usr/local/sbin:$PATH:/usr/local/share/npm/bin"
export EDITOR="subl"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# source z
source "$(brew --prefix)/etc/profile.d/z.sh"