# Path to your oh-my-zsh configuration.
ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load (in ~/.oh-my-zsh/themes/)
ZSH_THEME="oneend"

# Plugins to load (from oh-my-zsh)
plugins=(git zsh-syntax-highlighting)

# Source other files
source ${ZSH}/oh-my-zsh.sh
source ${HOME}/.zsh-alias
source ${HOME}/.rvm/scripts/rvm

# Disable autocorrect
unsetopt correct_all

# Set colors
LSCOLORS=hxfxcxdxbxegedabagacad

# Other settings
PATH="/usr/local/bin:$PATH"
EDITOR="vim"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH
PATH=$PATH:/usr/local/share/npm/bin # Add NPM to PATH
